version: "3"
services:
  bench:
    build:
      context: ./bench
    volumes:
    - ./bench:/home/isucon/isubata/bench
    depends_on:
      - nginx
    command: /bin/sh -c "while :; do sleep 10; done"
  app:
    build:
      context: ./webapp
    volumes:
      - ./webapp:/home/isucon/isubata/webapp
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    environment:
      ISUBATA_DB_HOST: db
      ISUBATA_DB_USER: isucon
      ISUBATA_DB_PASSWORD: isucon
      REDIS_HOST: redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
      - ./log/mysql:/var/log/mysql
      - ./files/db/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: isubata
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/conf.d/my.local.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx
      - ./webapp/public:/www/public
      #- ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    links:
      - "app"
